apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "shopping-cart.fullname" . }}-{{ .Values.color }}
  labels:
    app: {{ include "shopping-cart.fullname" . }}
    color: {{ .Values.color }}
spec:
  replicas: {{ .Values.hpa.minReplicas }}
  selector:
    matchLabels:
      app: {{ include "shopping-cart.fullname" . }}
      color: {{ .Values.color }}
  template:
    metadata:
      labels:
        app: {{ include "shopping-cart.fullname" . }}
        color: {{ .Values.color }}
    spec:
      containers:
        - name: shopping-cart
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          envFrom:
            - configMapRef:
                name: {{ include "shopping-cart.fullname" . }}-{{ .Values.color }}-config
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 30
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 90
            timeoutSeconds: 3

