image:
  repository: acruniquedemo12345.azurecr.io/shopcart
  tag: "v1"
  pullPolicy: IfNotPresent

# Blue/Green
color: blue

service:
  create: true
  type: LoadBalancer
  port: 8070
  targetPort: 8070
  activeColor: blue

env:
  SPRING_PROFILES_ACTIVE: "default"

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1024Mi

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  cpuUtilization: 60

